# Generated by Django 4.2.2 on 2023-08-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], default='Dog'),
            preserve_default=False,
        ),
    ]
