# Generated by Django 4.2.2 on 2023-07-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
