# Generated by Django 4.2.2 on 2023-08-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.CharField(blank=True, null=True),
        ),
    ]
