# Generated by Django 4.2.2 on 2023-07-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('logo', models.ImageField(default='./logo.png', upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
