# Generated by Django 4.2.2 on 2023-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
