# Generated by Django 4.2.2 on 2023-09-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_siteconfiguration_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(default='"../logo_fawisz.png', help_text='The logo next to the title', upload_to='images/'),
        ),
    ]
