# Generated by Django 4.2.2 on 2023-10-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_siteconfiguration_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='base_layout',
            field=models.CharField(choices=[('SIDE', 'side_navigation.html')], default='SIDE', max_length=4),
        ),
    ]
