# Generated by Django 5.0.6 on 2024-06-27 08:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_siteconfiguration_base_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='./logo_fawisz.png', help_text='The logo next to the title', max_length=255, verbose_name='image'),
        ),
    ]
