# Generated by Django 4.2.2 on 2023-07-13 04:54

import cms_public.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('template', models.FilePathField(match='.html$', path=cms_public.models.templates_path)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('default', models.TextField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms_public.layout')),
            ],
        ),
    ]
