# Generated by Django 4.2.2 on 2023-09-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_public', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('slug', 'layout')},
        ),
    ]
